"""base inicial sincronizada

Revision ID: 50ceeb4de263
Revises: 
Create Date: 2025-11-06 15:25:31.298374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50ceeb4de263'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta')
    op.drop_table('historial_inventario')
    op.drop_table('liquidacion_producto')
    op.drop_table('producto')
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entradas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('entradas_caja', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salidas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gastos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('caja_manual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prestamos_hoy', sa.Float(), nullable=True))
        batch_op.drop_column('entrada')
        batch_op.drop_column('salida')
        batch_op.drop_column('inventario_valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventario_valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('salida', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entrada', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('prestamos_hoy')
        batch_op.drop_column('caja_manual')
        batch_op.drop_column('gastos')
        batch_op.drop_column('salidas')
        batch_op.drop_column('entradas_caja')
        batch_op.drop_column('entradas')

    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('producto_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_inicial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unidades_restantes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('interes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vendidas_dia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_vendido_dia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='producto_pkey'),
    sa.UniqueConstraint('codigo', name='producto_codigo_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('liquidacion_producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('caja_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entrada_inventario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('salida_efectivo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('caja_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('inventario_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('liquidacion_producto_pkey')),
    sa.UniqueConstraint('fecha', name=op.f('liquidacion_producto_fecha_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('historial_inventario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('historial_inventario_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historial_inventario_pkey'))
    )
    op.create_table('venta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingreso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('venta_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('venta_pkey'))
    )
    # ### end Alembic commands ###
